version: '2.2'

services:
  backend:
    image: back:1
    environment:
      PG_NAME: db
      PG_USER: bruh
      PG_PASSWORD: bruh
      PG_HOST: database
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:14
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: bruh
      POSTGRES_PASSWORD: bruh
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "bruh"]