version: '3'
# or when an error occurs:
# version: '2.2'

services:
  backend:
    image: back:1
    environment:
      &dbenv
      PG_USER: bruh
      PG_PASSWORD: bruh
      PG_HOST: database
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: postgres:14
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: bruh
      POSTGRES_PASSWORD: bruh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "bruh"]

  migrations:
    image: back:1
    environment:
      <<: *dbenv
    command: sh -c "migrate -path ./schema -database 'postgres://bruh:bruh@0.0.0.0:5432/db?sslmode=disable' up"
    depends_on:
      - database
      - backend